name: Rust

on: [push]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout root project
      uses: actions/checkout@v1
    - name: Build
      run: sh scripts/build.sh

  Mac_OS_X:
    runs-on: macOS-latest
    steps:
    - name: Checkout root project
      uses: actions/checkout@v1
    - name: Build Project
      run: sh scripts/build.sh

  Windows:
    runs-on: windows-2016
    steps:
    - name: Checkout root project
      uses: actions/checkout@v1
    - name: Build
      run: cargo build

