name: Rust

on: [push]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout root project
      uses: actions/checkout@v1
    - name: Build
      run: |
        cargo build --all

  Mac_OS_X:
    runs-on: macOS-latest
    steps:
    - name: Checkout root project
      uses: actions/checkout@v1
    - name: Build Project
      run: |
        export PATH="$PATH/.cargo/bin:$PATH"
        cargo build --all

  Windows:
    runs-on: windows-2016
    steps:
    - name: Checkout root project
      uses: actions/checkout@v1
    - name: Build
      run: cargo build

